# Generated by Django 4.2 on 2025-10-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_promocode_promocode_store_promo_promo_c_37315d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='promo_amount',
            field=models.PositiveSmallIntegerField(default=10, help_text='Discount percent (e.g., 10 means 10%)'),
        ),
    ]
